---
title: "DA401"
output: html_document
date: "2023-03-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stringr)
library(dplyr)
library(caret)
library(rpart.plot)
library(rattle)
library(tidyr)
library(foreign)
library(ggplot2)
library(reshape2)
```

### Data cleaning
```{r}
data<-read.csv("mydata.csv")


for(i in 1:492){
  if(isTRUE(data$ST[i]=="Advance_Big_Advance")){
    data$Option[i] = "Big_Advance"
  }
  else if(data$ST[i]=="Double_Advance_Big_Advance"){
    data$Option[i] = "Big_Advance"
  }
  else if(data$ST[i]=="Double_Advance"){
    data$Option[i] = "No"
  }
  else{
    a = strsplit(data$ST[i],"_")
    data$Option[i] = a[[1]][length(a[[1]])]
  }
}

for(i in 1:492){
  if(data$OST[i]=="Advance_Big_Advance"){
    
    data$OptionO[i] = "Big_Advance"
  }
  else if(data$OST[i]=="Double_Advance"){
    data$OptionO[i] = "No"
  }
  else if(data$OST[i]=="Double_Advance_Big_Advance"){
    data$OptionO[i] = "Big_Advance"
  }
  else{
    a = strsplit(data$OST[i],"_")
    data$OptionO[i] = a[[1]][length(a[[1]])]
  }
}



for(i in 1:492){
  if(data$ST[i] == "Double_Advance"){
    data$Start[i]=data$ST[i]
  }
  else if(data$ST[i]=="Advance_Big_Advance"){
    data$Start[i]="Advance"
  }
  else if(data$ST[i]=="Double_Advance_Big_Advance"){
    data$Start[i]="Double_Advance"
  }
  else{
    b = str_length(data$ST[i]) - str_length(data$Option[i])-1
    data$Start[i] = substr(data$ST[i],1,b)
  }
}

for(i in 1:492){
  if(data$OST[i] == "Double_Advance"){
    data$OStart[i]=data$OST[i]
  }
  else if(data$OST[i]=="Advance_Big_Advance"){
    data$OStart[i]="Advance"
  }
  else if(data$OST[i]=="Double_Advance_Big_Advance"){
    data$OStart[i]="Double_Advance"
  }
  else{
    b = str_length(data$OST[i]) - str_length(data$OptionO[i])-1
    data$OStart[i] = substr(data$OST[i],1,b)
  }
}

for(i in 1:492){
  if(data$Option[i]=="No"){
    data$Launch[i]="Stop"
  }
  else if(data$Option[i]=="Big_Advance"){
    data$Launch[i] = "Launch"
  }
  else if(data$Option[i]=="Flunge"){
    data$Launch[i] = "Launch"
  }
  else{
    data$Launch[i]=data$Option[i]
  }
}

for(i in 1:492){
  if(data$OptionO[i]=="No"){
    data$LaunchO[i]="Stop"
  }
  else if(data$OptionO[i]=="Big_Advance"){
    data$LaunchO[i] = "Stop"
  }
  else if(data$OptionO[i]=="Flunge"){
    data$LaunchO[i] = "Launch"
  }
  else{
    data$LaunchO[i]=data$OptionO[i]
  }
}
for(i in 1:492){
  if(data$Start[i]=="Advance"){
    data$Tempo[i] = 1
  }
  else if(data$Start[i]=="Advance_Half_Step"){
    data$Tempo[i] = 1.5
  }
  else if(data$Start[i]=="Half_Step_Advance"){
    data$Tempo[i] = 1.5
  }
  else if(data$Start[i]=="Double_Advance"){
    data$Tempo[i] = 2
  }
  else if(data$Start[i]=="Double_Advance_Half_Step"){
    data$Tempo[i]=2.5
  }
}

for(i in 1:492){
  if(data$OStart[i]=="Advance"){
    data$OTempo[i] = 1
  }
  else if(data$OStart[i]=="Advance_Half_Step"){
    data$OTempo[i] = 1.5
  }
  else if(data$OStart[i]=="Half_Step_Advance"){
    data$OTempo[i] = 1.5
  }
  else if(data$OStart[i]=="Double_Advance"){
    data$OTempo[i] = 2
  }
  else if(data$OStart[i]=="Double_Advance_Half_Step"){
    data$OTempo[i]=2.5
  }
}

new_data<-select(data, Match_number, Target_Fencer, Opponents, Start, Option, Backfoot, OStart, OptionO, O_Backfoot,Outcome,Defense_movement,Place_When_Finish,Choice,Outcome.1,Launch,LaunchO,Tempo,OTempo)
```

```{r}
dataset1<-data.frame("Match_number", "Target_Fencer", "Opponents", "Start", "Option", "Backfoot", "OStart", "OptionO", "O_Backfoot","Outcome","Defense_movement","Place_When_Finish","Choice","Outcome.1","Launch","LaunchO","Tempo","OTempo")
a=0
for(i in seq(1,491,2)){
  TenRandomNumbers <- sort(sample.int(10,1))
  a=a+1
  if(TenRandomNumbers>5){
    dataset1[a,] = new_data[i,]
    }
  else{
    dataset1[a,] = new_data[i+1,]
  }
}

nlevels(factor(dataset1$X.Start.))
dataset2<-dataset1%>%select(2,3,4,5,6,7,8,9,10,15,16,17,18)
colnames(dataset2)<-c("Target","Opp","Stt","Opt","Bf","OStt","OptO","OBf","Result","Launch","LaunchO","Tempo","OTempo")
table(dataset2$Launch)
table(dataset2$Stt)
table(dataset2$Tempo)
```

```{r}
dataset3 <- data.frame(matrix(ncol = 3, nrow = 492))
colnames(dataset3) <- c('Target', 'Opp', 'Advance')
for(i in 1:492){
  dataset3$Target[i]=dataset2$Target[i]
}
for(i in 1:492){
  dataset3$Opp[i]=dataset2$Opp[i]
}
for(i in 1:492){
  if(new_data$Start[i] =="Advance"){
    dataset3$Advance[i]=1
  }
  else{
    dataset3$Advance[i]=0
  }
}
for(i in 1:492){
  if(new_data$Start[i] =="Double_Advance"){
    dataset3$Double_Advance[i]=1
  }
  else{
    dataset3$Double_Advance[i]=0
  }
}
for(i in 1:492){
  if(new_data$Start[i] =="Advance_Half_Step"){
    dataset3$Advance_Half_Step[i]=1
  }
  else{
    dataset3$Advance_Half_Step[i]=0
  }
}
for(i in 1:492){
  if(new_data$Start[i] =="Double_Advance_Half_Step"){
    dataset3$Double_Advance_Half_Step[i]=1
  }
  else{
    dataset3$Double_Advance_Half_Step[i]=0
  }
}
for(i in 1:492){
  if(new_data$Start[i] =="Half_Step_Advance"){
    dataset3$Half_Step_Advance[i]=1
  }
  else{
    dataset3$Half_Step_Advance[i]=0
  }
}



for(i in 1:492){
  if(new_data$OStart[i] =="Advance"){
    dataset3$AdvanceO[i]=1
  }
  else{
    dataset3$AdvanceO[i]=0
  }
}
for(i in 1:492){
  if(new_data$OStart[i] =="Double_Advance"){
    dataset3$Double_AdvanceO[i]=1
  }
  else{
    dataset3$Double_AdvanceO[i]=0
  }
}
for(i in 1:492){
  if(new_data$OStart[i] =="Advance_Half_Step"){
    dataset3$Advance_Half_StepO[i]=1
  }
  else{
    dataset3$Advance_Half_StepO[i]=0
  }
}
for(i in 1:492){
  if(new_data$OStart[i] =="Double_Advance_Half_Step"){
    dataset3$Double_Advance_Half_StepO[i]=1
  }
  else{
    dataset3$Double_Advance_Half_StepO[i]=0
  }
}
for(i in 1:492){
  if(new_data$OStart[i] =="Half_Step_Advance"){
    dataset3$Half_Step_AdvanceO[i]=1
  }
  else{
    dataset3$Half_Step_AdvanceO[i]=0
  }
}


for(i in 1:492){
  if(new_data$Launch[i] =="Launch"){
    dataset3$Launch[i]=1
  }
  else{
    dataset3$Launch[i]=0
  }
}

for(i in 1:492){
  if(new_data$Backfoot[i] =="Behind"){
    dataset3$Bf[i]=0
  }
  else if(new_data$Backfoot[i] =="On"){
    dataset3$Bf[i]=1
  }
  else{
    dataset3$Bf[i]=2
  }
}

for(i in 1:492){
  if(new_data$O_Backfoot[i] =="Behind"){
    dataset3$OBf[i]=0
  }
  else if(new_data$O_Backfoot[i] =="On"){
    dataset3$OBf[i]=1
  }
  else{
    dataset3$OBf[i]=2
  }
}

for(i in 1:492){
  if(dataset3$Bf[i] ==0){
    dataset3$Bf_Behind[i]=1
    dataset3$Bf_On[i]=0
    dataset3$Bf_Pass[i]=0
  }
  else if(dataset3$Bf[i] ==1){
    dataset3$Bf_Behind[i]=0
    dataset3$Bf_On[i]=1
    dataset3$Bf_Pass[i]=0
  }
  else if(dataset3$Bf[i] ==2){
    dataset3$Bf_Behind[i]=0
    dataset3$Bf_On[i]=0
    dataset3$Bf_Pass[i]=1
  }
}

for(i in 1:492){
  if(dataset3$OBf[i] ==0){
    dataset3$OBf_Behind[i]=1
    dataset3$OBf_On[i]=0
    dataset3$OBf_Pass[i]=0
  }
  else if(dataset3$OBf[i] ==1){
    dataset3$OBf_Behind[i]=0
    dataset3$OBf_On[i]=1
    dataset3$OBf_Pass[i]=0
  }
  else if(dataset3$OBf[i] ==2){
    dataset3$OBf_Behind[i]=0
    dataset3$OBf_On[i]=0
    dataset3$OBf_Pass[i]=1
  }
}
```

```{r}
table(dataset3$Launch)
dataset3<-select(dataset3, -Bf, -OBf)
dataset4<-data.frame("Target","Opp","Advance","Double_Advance","Advance_Half_Step","Double_Advance_Half_Step","Half_Step_Advance","AdvanceO","Double_AdvanceO","Advance_Half_StepO","Double_Advance_Half_StepO","Half_Step_AdvanceO","Launch","Bf_Behind","Bf_On","Bf_Pass","OBf_Behind","OBf_On","OBf_Pass")
a=0
for(i in seq(1,491,2)){
  TenRandomNumbers <- sort(sample.int(10,1))
  a=a+1
  if(TenRandomNumbers>5){
    dataset4[a,] = dataset3[i,]
    }
  else{
    dataset4[a,] = dataset3[i+1,]
  }
}

colnames(dataset4)<-c("Target","Opp","Advance","Double_Advance","Advance_Half_Step","Double_Advance_Half_Step","Half_Step_Advance","AdvanceO","Double_AdvanceO","Advance_Half_StepO","Double_Advance_Half_StepO","Half_Step_AdvanceO","Launch","Bf_Behind","Bf_On","Bf_Pass","OBf_Behind","OBf_On","OBf_Pass")

```

### Decision Tree
```{r}
set.seed(4)
index = createDataPartition(y=dataset4$Launch, p=0.8, list=FALSE)

train = dataset4[index,]
test =  dataset4[-index,]

```

```{r}
ctrl = trainControl(method="repeatedcv",number=20,repeats=10)
dtree_fit_pruning = train(Launch~Advance+Double_Advance+Half_Step_Advance+Advance_Half_Step+Double_Advance_Half_Step+AdvanceO+Double_AdvanceO+Half_Step_AdvanceO+Advance_Half_StepO+Double_Advance_Half_StepO+Bf_Behind+Bf_On+Bf_Pass+OBf_Behind+OBf_On+OBf_Pass, 
                          data = train, 
                          method = "rpart",
                          tuneLength = 20,
                          trControl = ctrl,
                         )

prp(dtree_fit_pruning$finalModel)
fancyRpartPlot(dtree_fit_pruning$finalModel)
```
### Results
```{r}
dtree_fit_pruning
predict<-predict(dtree_fit_pruning, newdata = test)
predict
confusionMatrix(predict,as.factor(test$Launch))
Importance = varImp(dtree_fit_pruning)
Importance
plot(Importance)
```

### Naive-Bayes with K fold CV
```{r}
library(e1071)
library(caTools)
library(caret)
```

```{r}
set.seed(32)
index = createDataPartition(y=dataset4$Launch, p=0.8, list=FALSE)

train = dataset4[index,]
test =  dataset4[-index,]
```

```{r}
x = select(train, Advance,Double_Advance,Half_Step_Advance,Advance_Half_Step,Double_Advance_Half_Step,AdvanceO,Double_AdvanceO,Half_Step_AdvanceO,Advance_Half_StepO,Double_Advance_Half_StepO,Bf_Behind,Bf_On,Bf_Pass,OBf_Behind,OBf_On,OBf_Pass )
y=as.factor(train$Launch)
```

### Results
```{r}
factorsdata <- mutate_all(x, as.factor)
testfactors <- mutate_all(test, as.factor)
model = train(factorsdata,y,'nb',trControl=trainControl(method='repeatedcv',number=10))

Pred <- predict(model, newdata = testfactors)
Pred
confusionMatrix(Pred, testfactors$Launch)
X = varImp(model)
X
plot(X)
```

### Naive-Bayes with LOOCV
```{r}
model1 = train(factorsdata,y,'nb',trControl=trainControl(method='LOOCV'))

Pred1 <- predict(model1, newdata = testfactors)
Pred1
confusionMatrix(Pred1, testfactors$Launch)
X = varImp(model1)
X
plot(X)
```




